import type { Metadata } from "next";
import Link from "next/link";
import { notFound } from "next/navigation";
import styles from "@/features/pre-dispatch/pre-dispatch.module.css";
import { preDispatchFlags } from "@/features/pre-dispatch/config";
import { getTenantDashboard, listTenantRequests, requireTenantCompany } from "@/features/pre-dispatch/repository";

export const metadata:Metadata={title:"Pre-Dispatch Inbox",robots:{index:false,follow:false}};
export const dynamic="force-dynamic";
export default async function Page({searchParams}:{searchParams:Promise<{q?:string;status?:string;page?:string}>}) {
  if(!preDispatchFlags.enabled)notFound();let company;try{company=await requireTenantCompany()}catch{return <main className={styles.shell}><section className={styles.panel}><h1>Sign in required</h1><p>Use your contractor account to open the Pre-Dispatch inbox.</p><Link className={styles.button} href="/login?returnTo=/portal/pre-dispatch">Sign in</Link></section></main>}
  const query=await searchParams;const page=Math.max(1,Number(query.page)||1);const [{requests,total,pageSize},metrics]=await Promise.all([listTenantRequests(company.id,{query:query.q,status:query.status,page}),getTenantDashboard(company.id)]);const totalPages=Math.max(1,Math.ceil(total/pageSize));
  const embed=`<div id="ggaurd-predispatch"></div>\n<script src="${process.env.NEXT_PUBLIC_APP_URL||"https://ggaurdai.com"}/widget/pre-dispatch.js" data-company="${company.public_widget_key}" async></script>`;
  const pageHref=(value:number)=>`?${new URLSearchParams({...(query.q?{q:query.q}:{}),...(query.status?{status:query.status}:{}),page:String(value)})}`;
  return <main className={styles.shell}><section className={styles.panel}><div className={styles.eyebrow}>{company.display_name}</div><h1>Pre-Dispatch dashboard</h1><p><Link href="/portal/pre-dispatch/settings">Widget and integration settings</Link> · <Link href="/portal/pre-dispatch/operations">Delivery operations</Link></p><div className={styles.grid3}><article className={styles.card}><strong>{Number(metrics.new_count)}</strong><br/>New requests</article><article className={styles.card}><strong>{Number(metrics.unassigned)}</strong><br/>Unassigned</article><article className={styles.card}><strong>{Number(metrics.awaiting_verification)}</strong><br/>Awaiting technician verification</article><article className={styles.card}><strong>{Number(metrics.last_seven_days)}</strong><br/>Submitted in 7 days</article><article className={styles.card}><strong>{Number(metrics.webhook_failures)+Number(metrics.notification_failures)}</strong><br/>Delivery failures</article><article className={styles.card}><strong>{Number(metrics.dead_letters)}</strong><br/>Dead-letter jobs</article></div><h2>Inbox</h2><form className={styles.formGrid}><div className={styles.field}><label>Search<input name="q" defaultValue={query.q}/></label></div><div className={styles.field}><label>Status<select name="status" defaultValue={query.status||""}><option value="">All</option>{["new","reviewed","contacted","scheduled","dispatched","completed","archived"].map(status=><option key={status}>{status}</option>)}</select></label></div><button className={styles.button}>Filter</button></form><div className={styles.requestList}>{requests.length?requests.map(request=><Link className={styles.request} key={request.id} href={`/portal/pre-dispatch/requests/${request.id}`}><span><strong>{request.public_reference} · Customer media request</strong><br/><span className={styles.muted}>{request.customer_name} · {request.service_address1}, {request.city}</span></span><span>{request.status}{request.assigned_auth_user_id?" · assigned":" · unassigned"}</span></Link>):<p className={styles.notice}>No requests match this view.</p>}</div><nav className={styles.actions} aria-label="Inbox pages">{page>1?<Link className={styles.buttonGhost} href={pageHref(page-1)}>Previous</Link>:null}<span>Page {page} of {totalPages} · {total} requests</span>{page<totalPages?<Link className={styles.buttonGhost} href={pageHref(page+1)}>Next</Link>:null}</nav><h2>Widget</h2><pre className={styles.code}>{embed}</pre></section></main>;
}
