"use client";
import { useEffect, useState } from "react";
import styles from "../pre-dispatch.module.css";
type Row=Record<string,unknown>;
type Readiness={name:string;ready:boolean;detail:string};
type Operations={readiness:Readiness[];outbox:Row[];webhooks:Row[];notifications:Row[]};
export function OperationsDashboard(){
  const[data,setData]=useState<Operations|null>(null);const[message,setMessage]=useState("");
  async function load(){const response=await fetch("/api/pre-dispatch/portal/operations");const body=await response.json();if(response.ok)setData(body);else setMessage(body.error)}
  useEffect(()=>{let active=true;fetch("/api/pre-dispatch/portal/operations").then(async response=>({response,body:await response.json()})).then(({response,body})=>{if(!active)return;if(response.ok)setData(body);else setMessage(body.error)}).catch(()=>{if(active)setMessage("Unable to load delivery operations.")});return()=>{active=false}},[]);
  async function replay(id:string){const response=await fetch("/api/pre-dispatch/portal/operations",{method:"PATCH",headers:{"content-type":"application/json"},body:JSON.stringify({id})});const body=await response.json();setMessage(response.ok?"Job queued for replay.":body.error);if(response.ok)await load()}
  if(!data)return <p aria-live="polite">{message||"Loading delivery operations…"}</p>;
  return <><p aria-live="polite">{message}</p><h2>Production readiness</h2><div className={styles.tableWrap}><table className={styles.table}><thead><tr><th>Dependency</th><th>Status</th><th>Owner / detail</th></tr></thead><tbody>{data.readiness.map(item=><tr key={item.name}><td>{item.name}</td><td>{item.ready?"Ready":"Action required"}</td><td>{item.detail}</td></tr>)}</tbody></table></div><h2>Background jobs</h2><div className={styles.tableWrap}><table className={styles.table}><thead><tr><th>Event</th><th>Status</th><th>Attempts</th><th>Error</th><th>Action</th></tr></thead><tbody>{data.outbox.map(row=><tr key={String(row.id)}><td>{String(row.event_type)}</td><td>{String(row.status)}</td><td>{String(row.attempts)}</td><td>{String(row.last_error_code||"—")}</td><td>{row.status==="dead_letter"?<button className={styles.buttonGhost} onClick={()=>void replay(String(row.id))}>Replay</button>:"—"}</td></tr>)}</tbody></table></div><h2>CRM webhook deliveries</h2><div className={styles.tableWrap}><table className={styles.table}><thead><tr><th>Endpoint</th><th>Status</th><th>Attempts</th><th>HTTP</th><th>Error</th></tr></thead><tbody>{data.webhooks.map(row=><tr key={String(row.id)}><td>{String(row.endpoint_url)}</td><td>{String(row.status)}</td><td>{String(row.attempts)}</td><td>{String(row.response_code||"—")}</td><td>{String(row.error_code||"—")}</td></tr>)}</tbody></table></div><h2>Email deliveries</h2><div className={styles.tableWrap}><table className={styles.table}><thead><tr><th>Destination</th><th>Status</th><th>Attempts</th><th>Error</th></tr></thead><tbody>{data.notifications.map(row=><tr key={String(row.id)}><td>{String(row.destination)}</td><td>{String(row.status)}</td><td>{String(row.attempts)}</td><td>{String(row.error_code||"—")}</td></tr>)}</tbody></table></div></>
}
