"use client";
import { FormEvent, useState } from "react";
import styles from "../pre-dispatch.module.css";

type Initial={status:string;assigned:boolean;scheduledAt:string|null;notes:string|null;verified:boolean;equipment:Record<string,unknown>|null};
export function RequestStatusForm({requestId,initial}:{requestId:string;initial:Initial}){
  const[message,setMessage]=useState("");const[busy,setBusy]=useState(false);
  async function save(event:FormEvent<HTMLFormElement>){event.preventDefault();setBusy(true);const data=new FormData(event.currentTarget);const response=await fetch(`/api/pre-dispatch/portal/requests/${requestId}`,{method:"PATCH",headers:{"content-type":"application/json"},body:JSON.stringify({status:data.get("status"),assignToMe:data.get("assignToMe")==="on",scheduledAt:data.get("scheduledAt")||undefined,technicianNotes:data.get("technicianNotes"),verifyEquipment:data.get("verifyEquipment")==="on",openerBrand:data.get("openerBrand"),doorWidthFeet:data.get("doorWidthFeet")||null,doorHeightFeet:data.get("doorHeightFeet")||null,counterbalanceSystem:data.get("counterbalanceSystem")})});const body=await response.json();setMessage(response.ok?"Workflow saved. Refresh to view the updated maintenance record.":body.error||"Unable to save workflow");setBusy(false)}
  const equipment=initial.equipment||{};
  return <form onSubmit={save} className={styles.card}><h2>Dispatch and technician workflow</h2><div className={styles.formGrid}><div className={styles.field}><label>Status<select name="status" defaultValue={initial.status}>{["new","reviewed","contacted","scheduled","dispatched","completed","archived"].map(value=><option key={value}>{value}</option>)}</select></label></div><div className={styles.field}><label>Scheduled time<input name="scheduledAt" type="datetime-local" defaultValue={initial.scheduledAt?initial.scheduledAt.slice(0,16):""}/></label></div><div className={`${styles.field} ${styles.full}`}><label><input name="assignToMe" type="checkbox" defaultChecked={initial.assigned}/> Assign this request to me</label></div><div className={`${styles.field} ${styles.full}`}><label>Technician notes<textarea name="technicianNotes" maxLength={4000} defaultValue={initial.notes||""} placeholder="Record the on-site findings. Do not rely on AI observations without inspection."/></label></div><div className={styles.field}><label>Verified opener brand<input name="openerBrand" defaultValue={String(equipment.openerBrand||"")}/></label></div><div className={styles.field}><label>Verified counterbalance system<select name="counterbalanceSystem" defaultValue={String(equipment.counterbalanceSystem||"unknown")}>{["unknown","standard_torsion","reverse_wound_torsion","wayne_dalton_torquemaster","extension_springs","other"].map(value=><option key={value} value={value}>{value.replaceAll("_"," ")}</option>)}</select></label></div><div className={styles.field}><label>Verified width (feet)<input name="doorWidthFeet" type="number" min="4" max="40" step="0.5" defaultValue={String(equipment.doorWidthFeet||"")}/></label></div><div className={styles.field}><label>Verified height (feet)<input name="doorHeightFeet" type="number" min="4" max="24" step="0.5" defaultValue={String(equipment.doorHeightFeet||"")}/></label></div><div className={`${styles.field} ${styles.full}`}><label><input name="verifyEquipment" type="checkbox" defaultChecked={initial.verified}/> I inspected the equipment and confirm these verified values</label></div></div><button className={styles.button} disabled={busy}>{busy?"Saving…":"Save workflow"}</button><p aria-live="polite">{message}</p></form>
}
