import { expect, test } from "@playwright/test";
import { readFileSync } from "node:fs";
import { resolve } from "node:path";
import { preDispatchAnalysisSchema } from "../../src/features/pre-dispatch/analysis-contract";
import { assertTenant, buildIntakeSummary, newInternalId, newPublicReference } from "../../src/features/pre-dispatch/domain";
import { retryDelayMs, signWebhookPayload, verifyWebhookSignature } from "../../src/features/pre-dispatch/events";
import { companySchema, mediaDeclarationSchema, normalizeEmail, normalizePhone, slugSchema } from "../../src/features/pre-dispatch/schemas";

test.describe("Pre-Dispatch domain security", () => {
  test("uses server-safe identifiers and unique-looking references", () => { expect(newInternalId()).toMatch(/^[0-9a-f-]{36}$/);const references=new Set<string>();for(let index=0;index<500;index++){const reference=newPublicReference();expect(reference).toMatch(/^GG-[2-9A-HJ-NP-Z]{6}$/);references.add(reference)}expect(references.size).toBe(500); });
  test("normalizes customer identifiers", () => { expect(normalizePhone("(602) 555-0100")).toBe("+16025550100");expect(normalizeEmail(" User@Example.COM ")).toBe("user@example.com"); });
  test("rejects unsafe media declarations", () => { expect(()=>slugSchema.parse("../admin")).toThrow();expect(()=>mediaDeclarationSchema.parse({originalFilename:"../x.jpg",mimeType:"image/jpeg",sizeBytes:20,type:"image"})).toThrow();expect(()=>mediaDeclarationSchema.parse({originalFilename:"x.jpg",mimeType:"video/mp4",sizeBytes:20,type:"image"})).toThrow(); });
  test("enforces tenant identity", () => { expect(()=>assertTenant("company-a","company-b")).toThrow(/Tenant/);expect(()=>assertTenant("company-a","company-a")).not.toThrow(); });
  test("builds a cautious free-text summary", () => { const value=buildIntakeSummary({description:"The door stopped opening this morning.",mediaCount:2});expect(value).toContain("Technician verification is required");expect(value).toContain("door stopped opening"); });
  test("discards client internal IDs", () => { const parsed=companySchema.parse({companyName:"Acme",contactName:"Alex Doe",workEmail:"a@acme.test",notificationEmail:"dispatch@acme.test",phone:"6025550100",websiteUrl:"",logoUrl:"",brandColor:"#0f766e",displayName:"Acme Garage",slug:"acme-garage",termsAccepted:true,company_id:"attacker"});expect("company_id" in parsed).toBe(false); });
  test("keeps customer matching and relationships tenant scoped in the database",()=>{const schema=readFileSync(resolve("neon/schema.sql"),"utf8");expect(schema).toContain("idx_pd_customers_phone ON pre_dispatch_customers(company_id, normalized_phone)");expect(schema).toContain("fk_pd_request_customer_tenant");expect(schema).toContain("fk_pd_media_session_tenant");expect(schema).toContain("fk_pd_media_request_tenant")});
  test("uses shared rate limits, malware scanning, retention, and revocable customer links",()=>{const schema=readFileSync(resolve("neon/schema.sql"),"utf8");const worker=readFileSync(resolve("src/features/pre-dispatch/worker.ts"),"utf8");const upload=readFileSync(resolve("src/app/api/pre-dispatch/uploads/route.ts"),"utf8");expect(schema).toContain("api_rate_limit_buckets");expect(schema).toContain("pre_dispatch_customer_access_tokens");expect(upload).toContain("scanPreDispatchMedia");expect(worker).toContain("processPreDispatchRetention");expect(worker).toContain("processing_status='pending' AND m.created_at<now()-interval '1 day'")});
  test("allows guided-camera-only submission and derives analyzable video frames",()=>{const intake=readFileSync(resolve("src/features/pre-dispatch/ui/IntakeForm.tsx"),"utf8");const compression=readFileSync(resolve("src/features/pre-dispatch/media-compression.ts"),"utf8");expect(intake).not.toMatch(/type="file" required/);expect(compression).toContain("extractVideoFrames");expect(compression).toContain("must be 60 seconds or shorter")});
  test("pins validated webhook DNS and never uses public references as authorization",()=>{const security=readFileSync(resolve("src/features/pre-dispatch/webhook-security.ts"),"utf8");const status=readFileSync(resolve("src/app/pre-dispatch/status/[token]/page.tsx"),"utf8");expect(security).toContain("postSafeWebhook");expect(security).toContain("lookup:");expect(status).toContain("verifyCustomerAccessToken");expect(status).toContain("revoked_at IS NULL")});
  test("binds iframe authorization to an exact parent origin and slug",()=>{const security=readFileSync(resolve("src/features/pre-dispatch/security.ts"),"utf8");expect(security).toContain('scope:"predispatch:embed"');expect(security).toContain("slug,origin");expect(security).toContain("new URL(claims.origin).origin!==claims.origin");expect(security).toContain("timingSafeEqual")});
  test("requires signed framing and avoids origin-reflecting preflight",()=>{const proxy=readFileSync(resolve("src/proxy.ts"),"utf8");const config=readFileSync(resolve("next.config.ts"),"utf8");const sessions=readFileSync(resolve("src/app/api/pre-dispatch/widget/sessions/route.ts"),"utf8");expect(proxy).toContain("verifyEmbedToken");expect(proxy).toContain("frame-ancestors ${claims.origin}");expect(config).not.toContain("frame-ancestors *");expect(sessions).not.toContain('"access-control-allow-origin":origin')});
});

test.describe("Pre-Dispatch public experience", () => {
  test("sales page renders", async({page}) => { await page.goto("/pre-dispatch");await expect(page.getByRole("heading",{name:/Know what’s waiting/})).toBeVisible(); });
  test("sample-only demo renders", async({page}) => { await page.goto("/pre-dispatch/demo");await expect(page.getByText("Sample data only")).toBeVisible(); });
  test("gated APIs fail closed by default", async({request}) => { const response=await request.post("/api/pre-dispatch/widget/sessions",{data:{companySlug:"missing-company"}});expect(response.status()).toBe(404); });
  test("widget preflight never reflects an unverified origin",async({request})=>{const response=await request.fetch("/api/pre-dispatch/widget/sessions",{method:"OPTIONS",headers:{origin:"https://attacker.example"}});expect(response.status()).toBe(204);expect(response.headers()["access-control-allow-origin"]).toBeUndefined()});
});

test.describe("Pre-Dispatch analysis and integrations", () => {
  test("validates combined rail-and-section height observations without parts advice", () => { const result=preDispatchAnalysisSchema.parse({potentialIssueDescription:"The evidence may indicate a spring-system issue; technician verification is required.",urgency:"high",safetyFlags:["Do not operate the door"],evidenceObservations:["Visible separation appears in the spring area."],equipmentObservations:{openerBrand:{value:"LiftMaster",confidence:.97,evidence:"LiftMaster logo is visible on the opener housing."},doorWidthFeet:{value:16,confidence:.72,evidence:"Full two-car opening is visible with standard panel proportions."},fullOpenerRailVisible:true,allDoorSectionsVisible:true,visibleSectionCount:4,doorHeightFeet:{value:7,confidence:.95,method:"rail_and_panel_geometry",evidence:"The complete rail, header connection, opening, and all four sections are visible."},counterbalanceSystem:{value:"standard_torsion",confidence:.94,evidence:"Exposed torsion shaft and spring are visible above the header."}},overallConfidence:.82,evidenceReferences:[],limitations:["Geometry provides an estimated, not measured, height."],technicianVerificationRequired:true});expect(result.equipmentObservations.doorHeightFeet.confidence).toBe(.95);expect(result.equipmentObservations.doorHeightFeet.method).toBe("rail_and_panel_geometry");expect("partsCategories" in result).toBe(false); });
  test("signs webhooks and rejects replayed timestamps", () => { const secret="test-secret-at-least-32-characters";const timestamp=String(Math.floor(Date.now()/1000));const body=JSON.stringify({eventId:newInternalId()});const signature=signWebhookPayload(secret,timestamp,body);expect(verifyWebhookSignature(secret,timestamp,body,`sha256=${signature}`)).toBe(true);expect(verifyWebhookSignature(secret,timestamp,body,signature,Date.now()+301_000)).toBe(false); });
  test("uses bounded exponential retry", () => { expect(retryDelayMs(1)).toBe(30_000);expect(retryDelayMs(2)).toBe(60_000);expect(retryDelayMs(20)).toBe(3_600_000); });
  test("keeps request and maintenance UUIDs distinct", () => { expect(newInternalId()).not.toBe(newInternalId()); });
});
