import Link from "next/link";
import { notFound } from "next/navigation";
import styles from "@/features/pre-dispatch/pre-dispatch.module.css";
import { getTenantRequest, listTenantMedia, requireTenantCompany } from "@/features/pre-dispatch/repository";
import { RequestStatusForm } from "@/features/pre-dispatch/ui/RequestStatusForm";
import { CustomerAccessControl } from "@/features/pre-dispatch/ui/CustomerAccessControl";
type Observation={value:string|number|null;confidence:number;evidence:string};
type Equipment={openerBrand:Observation;doorWidthFeet:Observation;doorHeightFeet:Observation;counterbalanceSystem:Observation};

export default async function Page({params}:{params:Promise<{requestId:string}>}) {
  const {requestId}=await params;let company;try{company=await requireTenantCompany()}catch{notFound()}
  const request=await getTenantRequest(company.id,requestId);if(!request)notFound();const media=await listTenantMedia(company.id,requestId);const equipment=request.equipment_observations as Equipment|null;
  return <main className={styles.shell}><section className={styles.panel}>
    <Link href="/portal/pre-dispatch">← Inbox</Link><div className={styles.eyebrow}>{request.public_reference}</div><h1>Customer media request</h1><RequestStatusForm requestId={request.id} initial={{status:request.status,assigned:Boolean(request.assigned_auth_user_id),scheduledAt:request.scheduled_at,notes:request.technician_notes,verified:Boolean(request.technician_verified_at),equipment:request.verified_equipment}}/>
    <div className={styles.grid3}><article className={styles.card}><h2>Customer</h2><p>{request.customer_name}<br/><a href={`tel:${request.customer_phone}`}>{request.customer_phone}</a>{request.customer_email?<><br/><a href={`mailto:${request.customer_email}`}>{request.customer_email}</a></>:null}</p></article><article className={styles.card}><h2>Service address</h2><p>{request.service_address1}<br/>{request.city}, {request.state} {request.postal_code}</p></article><article className={styles.card}><h2>Submitted</h2><p>{new Date(request.created_at).toLocaleString()}</p></article></div>
    <h2>What the customer reported</h2><p>{request.problem_description}</p><h2>Private evidence</h2>{media.length?<ul>{media.map(item=><li key={item.id}><a href={`/api/pre-dispatch/portal/media/${item.id}`} target="_blank" rel="noreferrer">Open {item.type}: {item.original_filename}</a> ({Math.ceil(Number(item.size_bytes)/1024)} KB)</li>)}</ul>:<p>No verified media.</p>}
    <div className={styles.report}><small>PRELIMINARY AI DESCRIPTION · TECHNICIAN VERIFICATION REQUIRED</small><h2>{request.analysis_status==="completed"?request.analysis_summary:`Analysis ${request.analysis_status}`}</h2>{request.urgency?<p><strong>Urgency:</strong> {request.urgency} · <strong>Confidence:</strong> {Math.round(Number(request.overall_confidence)*100)}%</p>:null}{request.safety_flags?.length?<p><strong>Safety concerns:</strong> {request.safety_flags.join(", ")}</p>:null}{request.evidence_observations?<><h3>Evidence observations</h3><p>{request.evidence_observations}</p></>:null}{equipment?<><h3>Equipment observations</h3><ul><li><strong>Opener brand:</strong> {String(equipment.openerBrand.value)} ({Math.round(equipment.openerBrand.confidence*100)}% confidence) — {equipment.openerBrand.evidence}</li><li><strong>Door size:</strong> {equipment.doorWidthFeet.value??"unknown"} ft wide × {equipment.doorHeightFeet.value??"unknown"} ft high</li><li><strong>Counterbalance system:</strong> {String(equipment.counterbalanceSystem.value).replaceAll("_"," ")} ({Math.round(equipment.counterbalanceSystem.confidence*100)}% confidence) — {equipment.counterbalanceSystem.evidence}</li></ul></>:null}{request.limitations?.length?<><h3>Limitations</h3><p>{request.limitations.join(" ")}</p></>:null}<p><strong>No parts or repair recommendation is generated.</strong> The technician determines required parts and work from the evidence and on-site inspection.</p></div>
    <div className={styles.card}><h2>Maintenance record</h2>{request.maintenance_record_id?<><p><strong>UUID:</strong> <code>{request.maintenance_record_id}</code></p><p>Status: {request.verification_state}</p></>:<p>Maintenance record creation is pending.</p>}<CustomerAccessControl requestId={request.id}/></div>
  </section></main>;
}
