import { redirect } from "next/navigation";
import { getCurrentUser } from "@/lib/auth/server";
import { getDb } from "@/lib/db";
import { hashBrokerInvite } from "@/lib/broker";

export const dynamic="force-dynamic";

async function claim(formData:FormData){"use server";const user=await getCurrentUser();const token=String(formData.get("token")||"");if(!user)redirect(`/auth/sign-in?next=/broker/claim/${encodeURIComponent(token)}`);const db=getDb();const rows=await db`SELECT d.id,d.company_id,d.contact_email,c.organization_id FROM broker_deals d JOIN pre_dispatch_companies c ON c.id=d.company_id WHERE d.invite_token_hash=${hashBrokerInvite(token)} AND d.invite_consumed_at IS NULL AND d.stage='invited' LIMIT 1`;const deal=rows[0];if(!deal)redirect(`/broker/claim/${encodeURIComponent(token)}?error=used`);if(!user.email||String(deal.contact_email).toLowerCase()!==user.email.toLowerCase())redirect(`/broker/claim/${encodeURIComponent(token)}?error=email`);const result=await db`WITH claimed AS (UPDATE broker_deals SET stage='claimed',claimed_at=now(),invite_consumed_at=now(),invite_token_hash=${`consumed:${deal.id}`},updated_at=now() WHERE id=${deal.id} AND invite_consumed_at IS NULL RETURNING company_id), profile_upsert AS (INSERT INTO profiles(id,full_name,role,organization_id) SELECT ${user.id},${user.name||null},'contractor',${deal.organization_id} FROM claimed ON CONFLICT(id) DO UPDATE SET full_name=COALESCE(EXCLUDED.full_name,profiles.full_name),role='contractor',organization_id=EXCLUDED.organization_id,updated_at=now() RETURNING id), membership AS (INSERT INTO pre_dispatch_company_users(id,company_id,auth_user_id,role) SELECT gen_random_uuid(),claimed.company_id,profile_upsert.id,'owner' FROM claimed CROSS JOIN profile_upsert ON CONFLICT(company_id,auth_user_id) DO UPDATE SET role='owner' RETURNING id) SELECT count(*)::int claimed FROM membership`;if(!Number(result[0]?.claimed))redirect(`/broker/claim/${encodeURIComponent(token)}?error=used`);redirect("/portal/pre-dispatch/settings")}
export default async function Page({params,searchParams}:{params:Promise<{token:string}>;searchParams:Promise<{error?:string}>}){const{token}=await params;const query=await searchParams;const user=await getCurrentUser();const rows=await getDb()`SELECT prospect_company,contact_email,stage,invite_consumed_at FROM broker_deals WHERE invite_token_hash=${hashBrokerInvite(token)} LIMIT 1`;const deal=rows[0];if(!deal||deal.invite_consumed_at||query.error==="used")return <main className="min-h-screen bg-slate-950 p-8 text-white"><div className="mx-auto max-w-xl rounded-2xl border border-slate-800 bg-slate-900 p-8"><h1 className="text-2xl font-bold">Invitation already used or unavailable</h1><p className="mt-3 text-slate-300">Ask the broker or GGuard support for a new invitation if you still need access.</p><a className="mt-5 inline-block text-cyan-300" href="mailto:support@ggaurdai.com">Contact support</a></div></main>;if(!user)redirect(`/auth/sign-in?next=/broker/claim/${encodeURIComponent(token)}`);return <main className="min-h-screen bg-slate-950 p-8 text-white"><div className="mx-auto max-w-xl rounded-2xl border border-slate-800 bg-slate-900 p-8"><h1 className="text-2xl font-bold">Claim {String(deal.prospect_company)}</h1><p className="mt-3 text-slate-300">This creates your contractor owner access and opens widget setup. You must be signed in as the invited email address.</p>{query.error==="email"?<div className="mt-4 rounded-lg bg-red-950 p-3 text-red-200"><p>Signed-in email does not match the invitation. Use {String(deal.contact_email)}.</p><a className="mt-2 inline-block underline" href={`/api/auth/sign-out?callbackURL=${encodeURIComponent(`/auth/sign-in?next=/broker/claim/${token}`)}`}>Sign out and switch account</a></div>:null}<form action={claim} className="mt-6"><input type="hidden" name="token" value={token}/><button className="w-full rounded-xl bg-cyan-500 p-3 font-semibold text-slate-950">Accept and configure widget</button></form></div></main>}
