import "server-only";
import { Resend } from "resend";
import { getDb } from "@/lib/db";
import { newInternalId } from "./security";
type EmailCompany = { id:string;notification_email:string;forwarding_email:string|null;additional_notification_emails:string[] };

const escape = (v: string) => v.replace(/[&<>'"]/g, (c) => ({"&":"&amp;","<":"&lt;",">":"&gt;","'":"&#39;",'"':"&quot;"})[c] || c);
export async function sendPreDispatchEmail(company: EmailCompany, request: { id: string; publicReference: string; customerName: string; phone: string; email?: string; address: string; category: string; description: string; summary: string; mediaCount: number }) {
  const sql = getDb(); const key = `request-created:${request.id}:email`; const exists = await sql`SELECT id, status FROM pre_dispatch_notification_deliveries WHERE idempotency_key = ${key}`;if(exists[0]&&["sent","mocked"].includes(String(exists[0].status)))return;
  const deliveryId = exists[0]?String(exists[0].id):newInternalId();if(!exists[0])await sql`INSERT INTO pre_dispatch_notification_deliveries (id, company_id, request_id, destination, idempotency_key) VALUES (${deliveryId}, ${company.id}, ${request.id}, ${company.notification_email}, ${key})`;
  const app = (process.env.NEXT_PUBLIC_APP_URL || "http://localhost:3000").replace(/\/$/, ""); const subject = `New pre-dispatch request: ${request.category} — ${request.customerName}`;
  const plain = `New pre-dispatch request ${request.publicReference}\nCustomer: ${request.customerName}\nPhone: ${request.phone}\nAddress: ${request.address}\nCategory: ${request.category}\n${request.description}\n${request.summary}\nMedia: ${request.mediaCount}\nTechnician verification is required.\n${app}/portal/pre-dispatch/requests/${request.id}`;
  const html = `<div style="font-family:system-ui;max-width:640px;margin:auto"><h1 style="color:#0f766e">New pre-dispatch request</h1><p><strong>${escape(request.publicReference)}</strong></p><p><strong>Customer:</strong> ${escape(request.customerName)}<br><strong>Phone:</strong> ${escape(request.phone)}${request.email ? `<br><strong>Email:</strong> ${escape(request.email)}` : ""}<br><strong>Address:</strong> ${escape(request.address)}</p><h2>${escape(request.category)}</h2><p>${escape(request.description)}</p><p>${escape(request.summary)}</p><p>${request.mediaCount} media item(s)</p><p><a href="${app}/portal/pre-dispatch/requests/${request.id}" style="background:#0f766e;color:white;padding:12px 18px;border-radius:8px;text-decoration:none">Open secure request</a></p><p style="color:#64748b;font-size:12px">This is preliminary information for dispatch. Technician verification is required.</p></div>`;
  try { const keyValue = process.env.RESEND_API_KEY; if (!keyValue) { console.info("[pre-dispatch email:development]", { deliveryId, subject }); await sql`UPDATE pre_dispatch_notification_deliveries SET status = 'mocked', attempts = 1, last_attempt_at = now(), updated_at = now() WHERE id = ${deliveryId}`; return; }
    const recipients=[company.notification_email,company.forwarding_email,...(company.additional_notification_emails||[])].filter((value,index,array):value is string=>Boolean(value)&&array.indexOf(value)===index);const result = await new Resend(keyValue).emails.send({ from: process.env.EMAIL_FROM || "GGuard <notifications@ggaurdai.com>", to: recipients, subject, html, text: plain }); if (result.error) throw new Error(result.error.message);
    await sql`UPDATE pre_dispatch_notification_deliveries SET status = 'sent', provider_message_id = ${result.data?.id || null}, attempts = attempts+1, last_attempt_at = now(), updated_at = now() WHERE id = ${deliveryId}`;
  } catch (error) { await sql`UPDATE pre_dispatch_notification_deliveries SET status = 'failed', attempts = attempts+1, last_attempt_at = now(), error_code = 'provider_error', updated_at = now() WHERE id = ${deliveryId}`; console.error("[pre-dispatch email] delivery failed", { deliveryId }); throw error; }
}
