import "server-only";
import { createHash } from "node:crypto";
import { getDb } from "@/lib/db";
import { getCurrentUser } from "@/lib/auth/server";
import { companySchema, intakeSchema, normalizeEmail, normalizePhone } from "./schemas";
import { createCustomerAccessToken, newInternalId, newPublicReference } from "./security";
import { buildIntakeSummary } from "./domain";
import { retryTransaction } from "@/lib/transaction-retry";
import { normalizePropertyAddress } from "@/lib/property-registry";
import { decryptPII, derivePIILookupHash, derivePropertyLookupHash, encryptPII } from "@/lib/pii-encryption";

export type Company = { id: string; organization_id: string | null; name: string; slug: string; display_name: string; contact_name:string|null;work_email:string|null;notification_email: string; forwarding_email:string|null;additional_notification_emails:string[];phone: string; website_url: string | null; logo_url: string | null; brand_color: string; public_widget_key: string; allowed_origins:string[];launcher_position:string;launcher_copy:string;welcome_message:string|null;retention_days:number;product_status:string;trial_ends_at:string;subscription_plan:string;active: boolean; widget_enabled: boolean };
export type RequestRow = { id: string; public_reference: string; customer_name: string; customer_phone: string; customer_email: string | null; service_address1: string; city: string; state: string; postal_code: string; problem_category: string; problem_description: string; status: string; intake_summary: string;analysis_status:string;analysis_id:string|null;analysis_summary:string|null;urgency:string|null;safety_flags:string[]|null;evidence_observations:string|null;equipment_observations:Record<string,unknown>|null;overall_confidence:number|null;limitations:string[]|null;maintenance_record_id:string|null;verification_state:string|null;assigned_auth_user_id:string|null;scheduled_at:string|null;technician_notes:string|null;technician_verified_at:string|null;verified_equipment:Record<string,unknown>|null;created_at: string };

export async function findPublicCompany(identifier: string): Promise<Company | null> {
  const sql = getDb(); const rows = await sql`SELECT * FROM pre_dispatch_companies WHERE (slug = ${identifier} OR public_widget_key::text = ${identifier}) AND active = true AND widget_enabled = true AND (product_status='active' OR (product_status='trial' AND trial_ends_at>now())) LIMIT 1`;
  return (rows[0] as Company | undefined) || null;
}
export async function findCompanyById(id: string): Promise<Company | null> { const sql=getDb();const rows=await sql`SELECT * FROM pre_dispatch_companies WHERE id=${id} AND active=true LIMIT 1`;return (rows[0] as Company|undefined)||null; }

export async function requireTenantCompany(): Promise<Company> {
  const user = await getCurrentUser(); if (!user) throw new Error("UNAUTHORIZED"); const sql = getDb();
  const rows = await sql`SELECT c.* FROM pre_dispatch_companies c JOIN pre_dispatch_company_users cu ON cu.company_id = c.id WHERE cu.auth_user_id = ${user.id} AND c.active = true AND (c.product_status='active' OR (c.product_status='trial' AND c.trial_ends_at>now())) LIMIT 1`;
  const company = rows[0] as Company | undefined; if (!company) throw new Error("FORBIDDEN"); return company;
}

export async function requireTenantManager(options: { allowExpiredBilling?: boolean } = {}): Promise<Company> {
  const user = await getCurrentUser(); if (!user) throw new Error("UNAUTHORIZED"); const sql = getDb();
  const rows = await sql`SELECT c.* FROM pre_dispatch_companies c JOIN pre_dispatch_company_users cu ON cu.company_id=c.id WHERE cu.auth_user_id=${user.id} AND cu.role IN ('owner','admin') AND c.active=true AND (${options.allowExpiredBilling === true} OR c.product_status='active' OR (c.product_status='trial' AND c.trial_ends_at>now())) LIMIT 1`;
  const company=rows[0] as Company|undefined;if(!company)throw new Error("FORBIDDEN");return company;
}

export async function createCompany(input: unknown) {
  const parsed = companySchema.parse(input); const user = await getCurrentUser(); if (!user) throw new Error("UNAUTHORIZED"); const sql = getDb();
  const profiles = await sql`SELECT p.organization_id,o.customer_type FROM profiles p LEFT JOIN organizations o ON o.id=p.organization_id WHERE p.id = ${user.id} LIMIT 1`; const organizationId = profiles[0]?.organization_id as string | undefined;
  if (!organizationId) throw new Error("A contractor organization is required");
  if (profiles[0]?.customer_type !== "contractor") throw new Error("Your account must belong to a contractor organization");
  const allowedOrigins=parsed.websiteUrl?[new URL(parsed.websiteUrl).origin]:[];
  const companyId = newInternalId(); const companyUserId = newInternalId();
  const auditId=newInternalId();const rows=await sql`WITH company AS (INSERT INTO pre_dispatch_companies (id,organization_id,name,slug,display_name,contact_name,work_email,notification_email,phone,website_url,logo_url,brand_color,allowed_origins) VALUES (${companyId},${organizationId},${parsed.companyName},${parsed.slug},${parsed.displayName},${encryptPII(parsed.contactName)},${encryptPII(parsed.workEmail.toLowerCase())},${parsed.notificationEmail.toLowerCase()},${normalizePhone(parsed.phone)},${parsed.websiteUrl||null},${parsed.logoUrl||null},${parsed.brandColor},${allowedOrigins}) RETURNING *), membership AS (INSERT INTO pre_dispatch_company_users(id,company_id,auth_user_id,role) SELECT ${companyUserId},id,${user.id},'owner' FROM company), audit_event AS (INSERT INTO pre_dispatch_audit_events(id,company_id,event_type,actor_type,sanitized_metadata) SELECT ${auditId},id,'company.created','company_user',${JSON.stringify({source:"self_service",originConfigured:allowedOrigins.length>0})}::jsonb FROM company) SELECT * FROM company`;
  return rows[0] as Company;
}

export async function getTenantWidgetHealth(companyId:string){const sql=getDb();const rows=await sql`SELECT c.id,c.widget_enabled,c.allowed_origins,c.product_status,c.trial_ends_at,(SELECT count(*)::int FROM pre_dispatch_upload_sessions s WHERE s.company_id=c.id) session_count,(SELECT max(s.created_at) FROM pre_dispatch_upload_sessions s WHERE s.company_id=c.id) last_session_at,(SELECT count(*)::int FROM pre_dispatch_requests r WHERE r.company_id=c.id) request_count,(SELECT max(r.created_at) FROM pre_dispatch_requests r WHERE r.company_id=c.id) last_request_at FROM pre_dispatch_companies c WHERE c.id=${companyId} LIMIT 1`;if(!rows[0])throw new Error("Company not found");return rows[0]}

export async function createUploadSession(company: Company, origin: string | null) {
  const sql = getDb(); const id = newInternalId(); const expiresAt = new Date(Date.now() + 30 * 60_000); const idempotencyKey = newInternalId();
  await sql`INSERT INTO pre_dispatch_upload_sessions (id, company_id, idempotency_key, origin, expires_at) VALUES (${id}, ${company.id}, ${idempotencyKey}, ${origin}, ${expiresAt})`;
  await audit(company.id, null, "widget.session.created", "customer", { sessionId: id }); return { id, expiresAt, idempotencyKey };
}

export async function assertSession(sessionId: string, companyId: string) {
  const sql = getDb(); const rows = await sql`SELECT * FROM pre_dispatch_upload_sessions WHERE id = ${sessionId} AND company_id = ${companyId} AND status = 'pending' AND expires_at > now() LIMIT 1`;
  if (!rows[0]) throw new Error("Upload session is invalid, expired, or finalized"); return rows[0];
}

export async function registerMedia(params: { companyId: string; sessionId: string; type: "image"|"video"; storageKey: string; originalFilename: string; safeFilename: string; mimeType: string; sizeBytes: number }) {
  await assertSession(params.sessionId, params.companyId); const sql = getDb(); const id = newInternalId();
  const maximum=params.type==="image"?5:1;
  await sql.transaction((tx)=>[
    tx`SELECT pg_advisory_xact_lock(hashtext(${params.sessionId}))`,
    tx`INSERT INTO pre_dispatch_media_assets (id,company_id,upload_session_id,type,storage_key,original_filename,safe_filename,mime_type,size_bytes) SELECT ${id},${params.companyId},${params.sessionId},${params.type},${params.storageKey},${params.originalFilename},${params.safeFilename},${params.mimeType},${params.sizeBytes} WHERE (SELECT count(*) FROM pre_dispatch_media_assets WHERE company_id=${params.companyId} AND upload_session_id=${params.sessionId} AND type=${params.type})<${maximum}`,
    tx`SELECT 1/(CASE WHEN EXISTS(SELECT 1 FROM pre_dispatch_media_assets WHERE id=${id} AND company_id=${params.companyId}) THEN 1 ELSE 0 END) AS declaration_guard`,
  ]);
  return { id, storageKey: params.storageKey };
}

export async function markMediaUploaded(mediaId: string, companyId: string, sessionId: string, sha256: string, scanProvider:string) {
  const sql = getDb(); const rows = await sql`UPDATE pre_dispatch_media_assets SET processing_status = 'verified',sha256=${sha256},verified_at=now(),malware_scan_status='clean',malware_scan_provider=${scanProvider},malware_scanned_at=now() WHERE id = ${mediaId} AND company_id = ${companyId} AND upload_session_id = ${sessionId} AND processing_status = 'pending' RETURNING id`;
  if (!rows[0]) throw new Error("Media does not belong to this upload session");
}

export async function finalizeRequest(input: unknown, companyId: string, sessionId: string) {
  const parsed = intakeSchema.parse(input); const sql = getDb();
  // A finalized session may be retried after the response is lost. Match both
  // tenant and signed session before returning the original request.
  const sessions = await sql`SELECT idempotency_key,status FROM pre_dispatch_upload_sessions WHERE id=${sessionId} AND company_id=${companyId} AND status IN ('pending','finalized') AND expires_at>now() LIMIT 1`;
  const session = sessions[0];
  if (!session) throw new Error("Upload session is invalid or expired");
  if (String(session.idempotency_key) !== parsed.idempotencyKey) throw new Error("Idempotency key does not match this session");
  const existing = await sql`SELECT id, public_reference FROM pre_dispatch_requests WHERE company_id = ${companyId} AND upload_session_id=${sessionId} AND idempotency_key = ${parsed.idempotencyKey} LIMIT 1`;
  if(existing[0]){const row=existing[0] as{id:string;public_reference:string};const access=createCustomerAccessToken(companyId,row.id);await sql`INSERT INTO pre_dispatch_customer_access_tokens(id,company_id,request_id,expires_at) VALUES(${access.claims.jti},${companyId},${row.id},${access.expiresAt})`;return{...row,duplicate:true,customerAccessToken:access.token}}
  const media = await sql`SELECT id,type,sha256 FROM pre_dispatch_media_assets WHERE company_id = ${companyId} AND upload_session_id = ${sessionId} AND id = ANY(${parsed.mediaAssetIds}::uuid[]) AND processing_status = 'verified' AND sha256 IS NOT NULL`;
  if (media.length !== parsed.mediaAssetIds.length) throw new Error("Every media asset must belong to this company and upload session");
  if (media.filter((m) => m.type === "image").length > 5 || media.filter((m) => m.type === "video").length > 1) throw new Error("Media count limit exceeded");
  const customerId = newInternalId(); const requestId = newInternalId(); const maintenanceId=newInternalId();const propertyCandidateId=newInternalId();const eventId=newInternalId();const auditId=newInternalId();const publicReference = newPublicReference();const access=createCustomerAccessToken(companyId,requestId);
  const summary = buildIntakeSummary({ description: parsed.problemDescription, mediaCount: media.length });
  const fullAddress=[parsed.serviceAddress1,parsed.serviceAddress2].filter(Boolean).join(" ");const addressKey=derivePropertyLookupHash(normalizePropertyAddress(fullAddress,parsed.postalCode));const encryptedAddress=encryptPII(fullAddress);const eventPayload=JSON.stringify({requestId,publicReference,maintenanceRecordId:maintenanceId});const mediaHashes=media.map(row=>String(row.sha256)).sort();const maintenanceHash=createHash("sha256").update(JSON.stringify({type:"pre_dispatch_intake",requestId,customerDescription:parsed.problemDescription,mediaHashes,verificationState:"technician_verification_pending"})).digest("hex");
  try{await retryTransaction(() => sql.transaction(tx=>[
    tx`INSERT INTO properties(id,address_key,street_address,postal_code,public_region) VALUES(${propertyCandidateId},${addressKey},${encryptedAddress},${parsed.postalCode.slice(0,5)},${`ZIP ${parsed.postalCode.slice(0,5)}`}) ON CONFLICT(address_key) DO NOTHING`,
    tx`INSERT INTO pre_dispatch_customers (id,company_id,first_name,last_name,phone,normalized_phone,email,normalized_email) VALUES(${customerId},${companyId},${encryptPII(parsed.firstName)},${encryptPII(parsed.lastName)},${encryptPII(parsed.mobilePhone)},${derivePIILookupHash("phone",normalizePhone(parsed.mobilePhone))},${parsed.email?encryptPII(parsed.email):null},${parsed.email?derivePIILookupHash("email",normalizeEmail(parsed.email)||""):null})`,
    tx`INSERT INTO pre_dispatch_requests (id,company_id,customer_id,property_id,upload_session_id,public_reference,idempotency_key,service_address1,service_address2,city,state,postal_code,preferred_contact_method,problem_category,problem_description,consent_accepted_at,ai_processing_consent,source,intake_summary,analysis_status)
      SELECT ${requestId},${companyId},${customerId},p.id,${sessionId},${publicReference},${parsed.idempotencyKey},${encryptPII(parsed.serviceAddress1)},${parsed.serviceAddress2?encryptPII(parsed.serviceAddress2):null},${parsed.city},${parsed.state},${parsed.postalCode},${parsed.preferredContactMethod||null},'Customer description',${parsed.problemDescription},now(),${parsed.aiProcessingConsent},'hosted',${summary},'pending' FROM properties p WHERE p.address_key=${addressKey} AND (SELECT count(*) FROM pre_dispatch_media_assets WHERE company_id=${companyId} AND upload_session_id=${sessionId} AND id=ANY(${parsed.mediaAssetIds}::uuid[]) AND processing_status='verified' AND sha256 IS NOT NULL)=${parsed.mediaAssetIds.length} AND EXISTS(SELECT 1 FROM pre_dispatch_upload_sessions WHERE id=${sessionId} AND company_id=${companyId} AND status='pending' AND expires_at>now())`,
    tx`INSERT INTO maintenance_records(id,public_id,repair_type,city,zip_code,content_hash,company_id,property_id,customer_id,pre_dispatch_request_id,source_media_hashes,verification_state,human_review_state) SELECT ${maintenanceId},${`PD-${publicReference.replace("GG-","")}`},'pre_dispatch_intake',city,postal_code,${maintenanceHash},company_id,property_id,customer_id,id,${mediaHashes},'technician_verification_pending','pending' FROM pre_dispatch_requests WHERE id=${requestId} AND company_id=${companyId}`,
    tx`UPDATE pre_dispatch_media_assets SET request_id=${requestId} WHERE company_id=${companyId} AND upload_session_id=${sessionId} AND id=ANY(${parsed.mediaAssetIds}::uuid[]) AND processing_status='verified'`,
    tx`UPDATE pre_dispatch_upload_sessions SET status='finalized',finalized_at=now() WHERE id=${sessionId} AND company_id=${companyId} AND status='pending'`,
    tx`INSERT INTO pre_dispatch_audit_events(id,company_id,request_id,event_type,actor_type,sanitized_metadata) SELECT ${auditId},${companyId},${requestId},'predispatch.request.created','customer',${JSON.stringify({eventVersion:1,publicReference})}::jsonb WHERE EXISTS(SELECT 1 FROM pre_dispatch_requests WHERE id=${requestId} AND company_id=${companyId})`,
    tx`INSERT INTO pre_dispatch_outbox_events(id,company_id,request_id,event_type,payload) SELECT ${eventId},${companyId},${requestId},'predispatch.request.finalized',${eventPayload}::jsonb WHERE EXISTS(SELECT 1 FROM pre_dispatch_requests WHERE id=${requestId} AND company_id=${companyId})`,
    tx`INSERT INTO pre_dispatch_customer_access_tokens(id,company_id,request_id,expires_at) SELECT ${access.claims.jti},${companyId},${requestId},${access.expiresAt} WHERE EXISTS(SELECT 1 FROM pre_dispatch_requests WHERE id=${requestId} AND company_id=${companyId})`,
    tx`SELECT 1/(CASE WHEN EXISTS(SELECT 1 FROM pre_dispatch_requests WHERE id=${requestId} AND company_id=${companyId}) THEN 1 ELSE 0 END) AS transaction_guard`
  ],{isolationLevel:"Serializable"}));}catch(error){const duplicate=await sql`SELECT id,public_reference FROM pre_dispatch_requests WHERE company_id=${companyId} AND upload_session_id=${sessionId} AND idempotency_key=${parsed.idempotencyKey} LIMIT 1`;if(duplicate[0]){const row=duplicate[0] as{id:string;public_reference:string};const retryAccess=createCustomerAccessToken(companyId,row.id);await sql`INSERT INTO pre_dispatch_customer_access_tokens(id,company_id,request_id,expires_at) VALUES(${retryAccess.claims.jti},${companyId},${row.id},${retryAccess.expiresAt})`;return{...row,duplicate:true,customerAccessToken:retryAccess.token}}throw error}
  return { id: requestId, public_reference: publicReference, duplicate: false,customerAccessToken:access.token };
}

function decryptRequest(row:RequestRow&{customer_first_name?:string;customer_last_name?:string}){return{...row,customer_name:`${decryptPII(String(row.customer_first_name||""))} ${decryptPII(String(row.customer_last_name||""))}`.trim(),customer_phone:decryptPII(row.customer_phone),customer_email:row.customer_email?decryptPII(row.customer_email):null,service_address1:decryptPII(row.service_address1)}}
export async function listTenantRequests(companyId:string,options:{query?:string;status?:string;page?:number;pageSize?:number}={}):Promise<{requests:RequestRow[];total:number;page:number;pageSize:number}>{const sql=getDb();const page=Math.max(1,options.page||1);const pageSize=Math.min(100,Math.max(10,options.pageSize||25));const offset=(page-1)*pageSize;const query=`%${(options.query||"").trim()}%`;const status=options.status||"";const rows=await sql`SELECT r.id,r.public_reference,c.first_name customer_first_name,c.last_name customer_last_name,c.phone customer_phone,c.email customer_email,r.service_address1,r.city,r.state,r.postal_code,r.problem_category,r.problem_description,r.status,r.intake_summary,r.analysis_status,r.assigned_auth_user_id,r.scheduled_at,r.technician_notes,r.technician_verified_at,r.verified_equipment,r.created_at,a.id analysis_id,a.summary analysis_summary,a.urgency,a.safety_flags,a.dispatch_notes evidence_observations,a.equipment_observations,a.overall_confidence,a.limitations,m.id maintenance_record_id,m.verification_state FROM pre_dispatch_requests r JOIN pre_dispatch_customers c ON c.id=r.customer_id AND c.company_id=r.company_id LEFT JOIN pre_dispatch_analyses a ON a.request_id=r.id AND a.company_id=r.company_id LEFT JOIN maintenance_records m ON m.pre_dispatch_request_id=r.id AND m.company_id=r.company_id WHERE r.company_id=${companyId} AND (${status}='' OR r.status=${status}) AND (${query}='%%' OR r.public_reference ILIKE ${query} OR r.city ILIKE ${query}) ORDER BY r.created_at DESC LIMIT ${pageSize} OFFSET ${offset}` as Array<RequestRow&{customer_first_name:string;customer_last_name:string}>;const totals=await sql`SELECT count(*) count FROM pre_dispatch_requests r WHERE r.company_id=${companyId} AND (${status}='' OR r.status=${status}) AND (${query}='%%' OR r.public_reference ILIKE ${query} OR r.city ILIKE ${query})`;return{requests:rows.map(decryptRequest),total:Number(totals[0].count),page,pageSize}}
export async function getTenantRequest(companyId:string,requestId:string):Promise<RequestRow|null>{const sql=getDb();const rows=await sql`SELECT r.id,r.public_reference,c.first_name customer_first_name,c.last_name customer_last_name,c.phone customer_phone,c.email customer_email,r.service_address1,r.city,r.state,r.postal_code,r.problem_category,r.problem_description,r.status,r.intake_summary,r.analysis_status,r.assigned_auth_user_id,r.scheduled_at,r.technician_notes,r.technician_verified_at,r.verified_equipment,r.created_at,a.id analysis_id,a.summary analysis_summary,a.urgency,a.safety_flags,a.dispatch_notes evidence_observations,a.equipment_observations,a.overall_confidence,a.limitations,m.id maintenance_record_id,m.verification_state FROM pre_dispatch_requests r JOIN pre_dispatch_customers c ON c.id=r.customer_id AND c.company_id=r.company_id LEFT JOIN pre_dispatch_analyses a ON a.request_id=r.id AND a.company_id=r.company_id LEFT JOIN maintenance_records m ON m.pre_dispatch_request_id=r.id AND m.company_id=r.company_id WHERE r.company_id=${companyId} AND r.id=${requestId} LIMIT 1` as Array<RequestRow&{customer_first_name:string;customer_last_name:string}>;return rows[0]?decryptRequest(rows[0]):null}
export async function getTenantDashboard(companyId:string){const sql=getDb();const summary=await sql`SELECT count(*) total,count(*) FILTER(WHERE status='new') new_count,count(*) FILTER(WHERE assigned_auth_user_id IS NULL AND status NOT IN ('completed','archived')) unassigned,count(*) FILTER(WHERE technician_verified_at IS NULL AND status IN ('dispatched','completed')) awaiting_verification,count(*) FILTER(WHERE created_at>=now()-interval '7 days') last_seven_days FROM pre_dispatch_requests WHERE company_id=${companyId}`;const operations=await sql`SELECT (SELECT count(*) FROM pre_dispatch_outbox_events WHERE company_id=${companyId} AND status='dead_letter') dead_letters,(SELECT count(*) FROM pre_dispatch_webhook_deliveries WHERE company_id=${companyId} AND status='failed') webhook_failures,(SELECT count(*) FROM pre_dispatch_notification_deliveries WHERE company_id=${companyId} AND status='failed') notification_failures`;return{...summary[0],...operations[0]}}
export async function listTenantMedia(companyId:string,requestId:string){const sql=getDb();return await sql`SELECT id,type,mime_type,original_filename,size_bytes FROM pre_dispatch_media_assets WHERE company_id=${companyId} AND request_id=${requestId} AND processing_status='verified' ORDER BY created_at ASC` as Array<{id:string;type:"image"|"video";mime_type:string;original_filename:string;size_bytes:number}>}
export async function getTenantMedia(companyId:string,mediaId:string){const sql=getDb();const rows=await sql`SELECT id,storage_key,mime_type,original_filename FROM pre_dispatch_media_assets WHERE company_id=${companyId} AND id=${mediaId} AND processing_status='verified' LIMIT 1`;return rows[0] as {id:string;storage_key:string;mime_type:string;original_filename:string}|undefined}
export async function updateTenantCompany(companyId:string,input:{notificationEmail:string;forwardingEmail?:string;additionalNotificationEmails?:string[];retentionDays?:number;logoUrl?:string;brandColor:string;welcomeMessage?:string;allowedOrigins:string[];widgetEnabled:boolean;launcherPosition:string;launcherCopy:string}){const origins=input.allowedOrigins.map(value=>{const url=new URL(value);if(url.protocol!=="https:"&&!(["localhost","127.0.0.1"].includes(url.hostname)&&process.env.NODE_ENV!=="production"))throw new Error("Allowed origins must use HTTPS");return url.origin});if(!/^#[0-9a-f]{6}$/i.test(input.brandColor))throw new Error("Invalid brand color");if(!["inline","bottom-right","bottom-left"].includes(input.launcherPosition))throw new Error("Invalid launcher position");if(input.logoUrl){const host=new URL(input.logoUrl).hostname;if(host!=="blob.vercelusercontent.com"&&!host.endsWith(".public.blob.vercel-storage.com"))throw new Error("Logo must use approved GGuard/Vercel Blob storage")}const retentionDays=Number(input.retentionDays||90);if(![30,60,90,180,365].includes(retentionDays))throw new Error("Invalid retention period");const additional=(input.additionalNotificationEmails||[]).map(value=>value.trim().toLowerCase()).filter(value=>/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(value)).slice(0,10);const sql=getDb();const rows=await sql`UPDATE pre_dispatch_companies SET notification_email=${input.notificationEmail.trim().toLowerCase()},forwarding_email=${input.forwardingEmail?.trim().toLowerCase()||null},additional_notification_emails=${additional},retention_days=${retentionDays},logo_url=${input.logoUrl||null},brand_color=${input.brandColor},welcome_message=${input.welcomeMessage||null},allowed_origins=${origins},widget_enabled=${input.widgetEnabled},launcher_position=${input.launcherPosition},launcher_copy=${input.launcherCopy.slice(0,80)},updated_at=now() WHERE id=${companyId} RETURNING *`;await audit(companyId,null,"widget.settings.updated","company_user",{originCount:origins.length,widgetEnabled:input.widgetEnabled});return rows[0] as Company}
export async function rotateTenantWidgetKey(companyId:string){const sql=getDb();const rows=await sql`UPDATE pre_dispatch_companies SET public_widget_key=gen_random_uuid(),updated_at=now() WHERE id=${companyId} RETURNING public_widget_key`;await audit(companyId,null,"widget.key.rotated","company_user",{});return String(rows[0].public_widget_key)}
export async function updateTenantRequestStatus(companyId: string, requestId: string, status: string) { const allowed = ["new","reviewed","contacted","scheduled","dispatched","completed","archived"]; if (!allowed.includes(status)) throw new Error("Invalid status"); const sql = getDb(); const rows = await sql`UPDATE pre_dispatch_requests SET status = ${status}, updated_at = now() WHERE id = ${requestId} AND company_id = ${companyId} RETURNING id`; if (!rows[0]) throw new Error("Request not found"); await audit(companyId, requestId, "request.status.updated", "company_user", { status }); }
export async function updateTenantRequestWorkflow(companyId:string,requestId:string,input:{status:string;assignToMe:boolean;scheduledAt?:string;technicianNotes?:string;verifyEquipment?:boolean;openerBrand?:string;doorWidthFeet?:number|null;doorHeightFeet?:number|null;counterbalanceSystem?:string}){const user=await getCurrentUser();if(!user)throw new Error("UNAUTHORIZED");const allowedStatuses=["new","reviewed","contacted","scheduled","dispatched","completed","archived"];if(!allowedStatuses.includes(input.status))throw new Error("Invalid status");const systems=["standard_torsion","reverse_wound_torsion","wayne_dalton_torquemaster","extension_springs","other","unknown"];if(input.verifyEquipment&&!systems.includes(input.counterbalanceSystem||""))throw new Error("Select the verified counterbalance system");const notes=(input.technicianNotes||"").trim().slice(0,4000);const scheduled=input.scheduledAt?new Date(input.scheduledAt):null;if(scheduled&&Number.isNaN(scheduled.getTime()))throw new Error("Invalid scheduled date");const verified=input.verifyEquipment?{openerBrand:(input.openerBrand||"unknown").trim().slice(0,100),doorWidthFeet:input.doorWidthFeet??null,doorHeightFeet:input.doorHeightFeet??null,counterbalanceSystem:input.counterbalanceSystem}:{};const sql=getDb();const membership=await sql`SELECT 1 FROM pre_dispatch_company_users WHERE company_id=${companyId} AND auth_user_id=${user.id} LIMIT 1`;if(!membership[0])throw new Error("FORBIDDEN");const rows=await sql`UPDATE pre_dispatch_requests SET status=${input.status},assigned_auth_user_id=${input.assignToMe?user.id:null},scheduled_at=${scheduled},technician_notes=${notes||null},technician_verified_at=${input.verifyEquipment?new Date():null},technician_verified_by=${input.verifyEquipment?user.id:null},verified_equipment=${JSON.stringify(verified)}::jsonb,updated_at=now() WHERE id=${requestId} AND company_id=${companyId} RETURNING id`;if(!rows[0])throw new Error("Request not found");if(input.verifyEquipment)await sql`UPDATE maintenance_records SET verification_state='technician_verified',human_review_state='verified',reviewed_at=now(),reviewed_by=${user.id} WHERE pre_dispatch_request_id=${requestId} AND company_id=${companyId}`;await audit(companyId,requestId,input.verifyEquipment?"request.technician_verified":"request.workflow.updated","company_user",{status:input.status,assignedToSelf:input.assignToMe,scheduled:Boolean(scheduled),equipmentVerified:Boolean(input.verifyEquipment)})}
export async function audit(companyId: string, requestId: string|null, eventType: string, actorType: string, metadata: Record<string, unknown>) { const sql = getDb(); await sql`INSERT INTO pre_dispatch_audit_events (id, company_id, request_id, event_type, actor_type, sanitized_metadata) VALUES (${newInternalId()}, ${companyId}, ${requestId}, ${eventType}, ${actorType}, ${JSON.stringify(metadata)}::jsonb)`; }
