import { createHash,randomBytes } from "node:crypto";
import { redirect } from "next/navigation";
import { revalidatePath } from "next/cache";
import { requireTenantManager } from "@/features/pre-dispatch/repository";
import { getCurrentUser } from "@/lib/auth/server";
import { getDb } from "@/lib/db";
export const dynamic="force-dynamic";

const hash=(value:string)=>createHash("sha256").update(value).digest("hex");
async function inviteMember(formData:FormData){"use server";const company=await requireTenantManager();const user=await getCurrentUser();if(!user)redirect("/auth/sign-in");const email=String(formData.get("email")||"").trim().toLowerCase();const role=String(formData.get("role")||"member");if(!/^\S+@\S+\.\S+$/.test(email)||!["admin","member"].includes(role))return;const token=randomBytes(32).toString("base64url");await getDb()`INSERT INTO pre_dispatch_team_invites(id,company_id,email,role,token_hash,invited_by,expires_at) VALUES(gen_random_uuid(),${company.id},${email},${role},${hash(token)},${user.id},now()+interval '7 days')`;redirect(`/portal/pre-dispatch/team?invite=${encodeURIComponent(token)}`)}
async function revokeInvite(formData:FormData){"use server";const company=await requireTenantManager();await getDb()`UPDATE pre_dispatch_team_invites SET revoked_at=now() WHERE id=${String(formData.get("inviteId"))} AND company_id=${company.id} AND consumed_at IS NULL`;revalidatePath("/portal/pre-dispatch/team")}
async function removeMember(formData:FormData){"use server";const company=await requireTenantManager();const user=await getCurrentUser();const memberId=String(formData.get("memberId"));if(!user||memberId===user.id)return;await getDb()`DELETE FROM pre_dispatch_company_users WHERE company_id=${company.id} AND auth_user_id=${memberId} AND role<>'owner'`;revalidatePath("/portal/pre-dispatch/team")}
export default async function Page({searchParams}:{searchParams:Promise<{invite?:string}>}){const company=await requireTenantManager();const query=await searchParams;const db=getDb();const[members,invites]=await Promise.all([db`SELECT cu.auth_user_id,cu.role,p.full_name FROM pre_dispatch_company_users cu LEFT JOIN profiles p ON p.id=cu.auth_user_id WHERE cu.company_id=${company.id} ORDER BY cu.role,p.full_name`,db`SELECT id,email,role,expires_at FROM pre_dispatch_team_invites WHERE company_id=${company.id} AND consumed_at IS NULL AND revoked_at IS NULL AND expires_at>now() ORDER BY created_at DESC`]);const app=process.env.NEXT_PUBLIC_APP_URL||"https://ggaurdai.com";const link=query.invite?`${app}/pre-dispatch/team/claim/${query.invite}`:null;return <main className="min-h-screen bg-slate-950 p-8 text-white"><div className="mx-auto max-w-4xl space-y-7"><div><a href="/portal/pre-dispatch/settings" className="text-cyan-300">← Settings</a><h1 className="mt-3 text-3xl font-bold">Team access</h1><p className="text-slate-400">Invite dispatchers and technicians without sharing owner credentials.</p></div>{link?<div className="rounded-xl border border-emerald-700 bg-emerald-950 p-4"><strong>Copy this one-time link now</strong><p className="mt-2 break-all font-mono text-sm">{link}</p></div>:null}<form action={inviteMember} className="grid gap-3 rounded-xl border border-slate-800 bg-slate-900 p-5 md:grid-cols-3"><input className="field md:col-span-2" type="email" name="email" placeholder="Team member email" required/><select className="field" name="role"><option value="member">Dispatcher/technician</option><option value="admin">Company administrator</option></select><button className="rounded-lg bg-cyan-500 p-3 font-semibold text-slate-950 md:col-span-3">Create seven-day invitation</button></form><section><h2 className="text-xl font-bold">Members</h2><div className="mt-3 space-y-2">{members.map(row=><div key={String(row.auth_user_id)} className="flex justify-between rounded-xl border border-slate-800 bg-slate-900 p-4"><span>{String(row.full_name||row.auth_user_id)} · {String(row.role)}</span>{row.role!=="owner"?<form action={removeMember}><input type="hidden" name="memberId" value={String(row.auth_user_id)}/><button className="text-red-300">Remove</button></form>:null}</div>)}</div></section><section><h2 className="text-xl font-bold">Pending invitations</h2><div className="mt-3 space-y-2">{invites.map(row=><div key={String(row.id)} className="flex justify-between rounded-xl border border-slate-800 bg-slate-900 p-4"><span>{String(row.email)} · {String(row.role)} · expires {new Date(String(row.expires_at)).toLocaleDateString()}</span><form action={revokeInvite}><input type="hidden" name="inviteId" value={String(row.id)}/><button className="text-amber-300">Revoke</button></form></div>)}</div></section></div></main>}
