import Link from "next/link";
import { Header } from "@/components/layout/Header";
import { Footer } from "@/components/layout/Footer";

export const metadata = { title: "Terms of Service | GGuardAI" };

export default function TermsPage() {
  return <><Header /><main className="bg-slate-950 py-12"><article className="mx-auto max-w-3xl space-y-7 px-4 text-slate-300"><div><p className="text-sm font-semibold text-cyan-300">Effective July 13, 2026</p><h1 className="mt-2 text-3xl font-bold text-white">Terms of Service</h1><p className="mt-3">These terms govern use of GGuardAI assessments, organization portals, reports, and property-ledger services.</p></div><section><h2 className="text-xl font-bold text-white">Diagnostic scope</h2><p className="mt-2">GGuardAI provides informational, remote assessments based on submitted evidence. A report is not an on-site inspection, engineering opinion, safety certification, warranty, or instruction to perform hazardous repairs. Stop using unsafe equipment and contact a qualified professional when immediate risk is present.</p></section><section><h2 className="text-xl font-bold text-white">Accounts and submissions</h2><p className="mt-2">You must provide accurate information, protect account access, and submit only records and media you are authorized to use. Repair and invoice submissions are attributed to the signed-in account and may be visible to authorized organization members.</p></section><section><h2 className="text-xl font-bold text-white">Payments and refunds</h2><p className="mt-2">Prices are shown before checkout and payments are processed by Stripe. Eligibility for refunds follows the <Link className="font-semibold text-cyan-300 underline" href="/refund-policy">Refund Policy</Link>.</p></section><section><h2 className="text-xl font-bold text-white">Ledger and verification</h2><p className="mt-2">Ledger hashes are designed to reveal later modification of recorded content. Development or mock anchors are not representations of a public blockchain transaction, ownership interest, cryptocurrency, NFT, or government credential.</p></section><section><h2 className="text-xl font-bold text-white">Acceptable use and liability</h2><p className="mt-2">You may not submit fraudulent records, access another organization’s data, disrupt the service, or use reports to misrepresent licensing or completed work. To the extent permitted by law, GGuardAI is not liable for repair decisions, contractor performance, or conditions not visible in submitted evidence.</p></section><section><h2 className="text-xl font-bold text-white">Contact</h2><p className="mt-2">Questions may be sent to <a className="font-semibold text-cyan-300 underline" href="mailto:support@ggaurdai.com">support@ggaurdai.com</a>.</p></section></article></main><Footer /></>;
}
