import type { Metadata } from "next";
import Link from "next/link";
import styles from "@/features/pre-dispatch/pre-dispatch.module.css";

export const metadata:Metadata={title:"GGuard Pre-Dispatch | Know What’s Waiting",description:"Collect customer photos, short videos, and structured service details before sending a garage door technician."};
const benefits=[{title:"For owners",body:"Fit better job information into your current process without replacing the tools your team already uses."},{title:"For dispatchers",body:"Receive one structured request with contact details, symptoms, urgency indicators, and media."},{title:"For technicians",body:"Review customer-provided context before the visit and verify every condition safely on site."}];
export default function PreDispatchPage(){return <main className={styles.shell}>
  <div className={styles.notice}><strong>For contractor websites: GGuard Pre-Dispatch.</strong> This is an intake widget subscription, not GGuard Diagnostics. <Link href="/diagnostics">Looking for an expert-reviewed repair assessment?</Link></div>
  <nav className={styles.nav}><Link className={styles.brand} href="/">GGuard AI · Pre-Dispatch</Link><div className={styles.navlinks}><Link className={styles.buttonGhost} href="/broker/apply">Sell GGuard</Link><Link className={styles.buttonGhost} href="/pre-dispatch/demo">Try demo</Link><Link className={styles.button} href="/pre-dispatch/get-started">Add Pre-Dispatch</Link></div></nav>
  <section className={styles.hero}><div className={styles.eyebrow}>AI-ready service intake</div><h1>Know what’s waiting before you dispatch.</h1><p className={styles.lead}>Let customers send a short video or a few photos before the appointment. GGuard turns each submission into a structured request your team can review before rolling a truck.</p><div className={styles.actions}><Link className={styles.button} href="/pre-dispatch/get-started">Start 30-day pilot</Link><Link className={styles.buttonGhost} href="/pre-dispatch/demo">Try the demo</Link></div></section>
  <section className={styles.section}><div className={styles.eyebrow}>Built for the whole service team</div><h2>Cleaner information before the truck rolls</h2><div className={styles.grid3}>{benefits.map(item=><article className={styles.card} key={item.title}><h3>{item.title}</h3><p>{item.body}</p></article>)}</div></section>
  <section className={styles.section}><div className={styles.eyebrow}>How it works</div><h2>Three steps from customer to dispatcher</h2><div className={styles.grid3}>{["1. Share","2. Customer shows","3. Team reviews"].map((title,index)=><article className={styles.card} key={title}><h3>{title}</h3><p>{["Use a branded hosted link or paste one small widget snippet onto your site.","They add details, photos or a short video, and explicit consent.","Your notification email and secure inbox receive the structured request."][index]}</p></article>)}</div><div className={styles.report}><small>SAMPLE · GG-7K4M92</small><h3>Door will not open · Vehicle may be trapped</h3><p>Customer reports a loud bang and a door that will not open. Three photos and one video were submitted. Prioritize dispatcher review. Technician verification is required.</p></div></section>
  <section className={styles.section}><h2>Works with your current workflow</h2><p className={styles.sectionLead}>Email and a focused inbox are included. Generic signed webhooks are available. Zapier, Make, SMS, ServiceTitan, Housecall Pro, Jobber, FieldEdge, and Service Fusion connections are planned—not currently included.</p><div className={styles.grid3}><article className={styles.card}><h3>Private by default</h3><p>Media uses private storage intent and time-limited access. Company records are tenant-scoped.</p></article><article className={styles.card}><h3>Safer guidance</h3><p>Customers are never asked to touch springs, cables, brackets, or an unstable door.</p></article><article className={styles.card}><h3>Preliminary, not diagnostic</h3><p>Intake summaries help dispatch. They do not replace inspection or technician verification.</p></article></div></section>
  <section id="pricing" className={styles.section}><div className={styles.eyebrow}>Pre-Dispatch widget subscription</div><h2>$149 per month or $1,490 per year</h2><p className={styles.sectionLead}>This price purchases access to the Pre-Dispatch website widget and hosted intake workflow. It is not a bundle of diagnostic report credits. Start with a 30-day pilot. Standard setup, one contractor brand, approved website origins, secure inbox/email delivery, team access, and standard support are included. Custom integrations and multi-brand deployments require a separate quote.</p><div className={styles.actions}><Link className={styles.button} href="/pre-dispatch/get-started">Start widget onboarding</Link></div></section>
  <section className={`${styles.section} ${styles.faq}`}><h2>Frequently asked questions</h2><details><summary>Does this diagnose the garage door problem?</summary><p>No. It organizes customer-reported information and media for preliminary dispatch review. A qualified technician must verify the issue.</p></details><details><summary>Do we need a new CRM?</summary><p>No. Email and a focused intake inbox are included.</p></details><details><summary>Can it work on our existing website?</summary><p>The launcher is designed for common HTTPS website builders and includes a hosted-page fallback. Each exact website origin must be approved and tested.</p></details><details><summary>How long is media retained?</summary><p>The contractor selects a supported retention period in settings. Deletion and legal-hold exceptions follow the applicable terms and privacy policy.</p></details></section>
  <footer className={styles.footer}><Link href="/privacy">Privacy</Link> · <Link href="/terms">Terms</Link> · <Link href="/support">Support</Link></footer>
</main>}
