-- Run only after PRE_DISPATCH_* flags are disabled and private media retention is handled.
ALTER TABLE maintenance_records DROP COLUMN IF EXISTS human_review_state;
ALTER TABLE maintenance_records DROP COLUMN IF EXISTS reviewed_by;
ALTER TABLE maintenance_records DROP COLUMN IF EXISTS reviewed_at;
ALTER TABLE maintenance_records DROP COLUMN IF EXISTS model_version;
ALTER TABLE maintenance_records DROP COLUMN IF EXISTS verification_state;
ALTER TABLE maintenance_records DROP COLUMN IF EXISTS safety_flags;
ALTER TABLE maintenance_records DROP COLUMN IF EXISTS preliminary_findings;
ALTER TABLE maintenance_records DROP COLUMN IF EXISTS source_media_hashes;
ALTER TABLE maintenance_records DROP COLUMN IF EXISTS analysis_id;
ALTER TABLE maintenance_records DROP COLUMN IF EXISTS pre_dispatch_request_id;
ALTER TABLE maintenance_records DROP COLUMN IF EXISTS customer_id;
ALTER TABLE maintenance_records DROP COLUMN IF EXISTS property_id;
ALTER TABLE maintenance_records DROP COLUMN IF EXISTS company_id;
DROP TABLE IF EXISTS pre_dispatch_webhook_deliveries;
DROP TABLE IF EXISTS pre_dispatch_customer_access_tokens;
DROP TABLE IF EXISTS pre_dispatch_webhook_configs;
DROP TABLE IF EXISTS pre_dispatch_outbox_events;
DROP TABLE IF EXISTS pre_dispatch_audit_events;
DROP TABLE IF EXISTS pre_dispatch_integration_deliveries;
DROP TABLE IF EXISTS pre_dispatch_notification_deliveries;
DROP TABLE IF EXISTS pre_dispatch_media_assets;
DROP TABLE IF EXISTS pre_dispatch_analyses;
DROP TABLE IF EXISTS pre_dispatch_requests;
DROP TABLE IF EXISTS pre_dispatch_upload_sessions;
DROP TABLE IF EXISTS pre_dispatch_customers;
DROP TABLE IF EXISTS pre_dispatch_company_users;
DROP TABLE IF EXISTS pre_dispatch_companies;
DROP TABLE IF EXISTS api_rate_limit_buckets;
